  - name: Install essential packages
    apt:
      state: latest
      pkg:
      - vim
      - curl
      - htop
      - git
      - mc
      - build-essential
      - net-tools
      - gettext
      - tree
      - avahi-daemon
